### ISSUE TITLE
[INFRASTRUCTURE] - Separate projects for DependencyInjection

### ISSUE THREAD

**Issue by rafsanulhasan** [hassanhabib/Standard.AI.OpenAI#103]
Can we have a separate project for Dependency Injection?

In .NET community, this pattern is pretty common:
1. We have a library for General Purpose programming i.e. like in a Console App (let assume ours **Standard.OpenAI**)
2. We need a separate library in order for the **Standard.OpenAI** library to work with ASP.NET Core and its dependency injection framework. (Standard.OpenAI.AspNetCore)

Some examples:
1. HotChocolate, HotChocolate.AspNetCore
2. Newtonsoft.Json, Microsoft.AspnetCore.Mvc.NewtonsoftJson
3. ReactiveUI, ReactiveUI.Blazor, ReactiveUI.Maui

**Comment by hassanhabib** [comment]
Agreed - out of the scope of this project however.
