### ISSUE TITLE
[INFRASTRUCTURE] - Testing Libraries

### ISSUE THREAD

**Issue by rafsanulhasan** [hassanhabib/Standard.AI.OpenAI#105]
Can we use
- Shouldly or FluentAssertions for assertion? It gives us a much cleaner and readability. 
  ```csharp
     var expected = "expected";
     var actual = RunBusinessLogic();
     actual.ShouldBe(expected);
  ```
- Faker for real-looking test data and AutoFixture for randomly generated data
  ```csharp
     var expected = Faker.Name.FirstName;
  ```
- NSubstitute as a mocking library. Very easy to use for beginners.
  ```csharp
     var dependentService = Substitute.For<IService>();
     dependentService
           .SomeMethod()
           .ReturnsForAnyArgs("b");
     dependentService
           .SomeMethod2("abc")
           .Returns("b");
     dependentService
            .ReceivedWithAnyArgs(1)
            .SomeMethod3();
     dependentService
            .Received(1)
            .SomeMethod4("abc");
  ```

**Comment by StefH** [comment]
Personal preference
- FluentAssertions 
- Moq

**Comment by jodendaal** [comment]
AutoFixture is great just tried it out in my tests. Saves alot of time rather than manually creating random objects. @StefH been using wiremock.net 💯. Great work. Autofixture + witemock makes simple acceptance tests. Couple of lines of code.

**Comment by hassanhabib** [comment]
At this point of the project we will be using `Moq` and `WireMock` with `FluentAssertions`
We also use `ObjectFiller` - but I will research `Faker` with The Standard Community for future projects.

Closing this issue.
