### ISSUE TITLE
DOCUMENTATIONS: Find Accounts of Hassan Habib And Link Them

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#140]
![image](https://user-images.githubusercontent.com/52498074/226825700-dacf4b85-15c2-4925-82a3-c4a09aaae3fa.png)

This section in readme just shows the text, make them Markdown links to refer the accounts of Hassan Habib in corresponding platforms

**Comment by ElbekDeveloper** [comment]
https://www.markdownguide.org/basic-syntax/

**Comment by glhays** [comment]
[YouTube](https://www.youtube.com/channel/UCT917nto6RSXMbnxToeKXWQ?&ab_channel=HassanHabib)

[LinkedIn](https://www.linkedin.com/in/hassanrezkhabib/)

[Twitch]()

[Twitter](https://twitter.com/hassanrezkhabib)

[Facebook](https://www.facebook.com/hassan.rezk.habib)

^^^^^^^ Markup ^^^^^^^

@hassanhabib @ElbekDeveloper can not seem to find the Twitch channel link.

**Comment by icnocop** [comment]
Twitch channel: https://www.twitch.tv/binhabib

**Comment by AbbosHaydarov** [comment]
I got it @ElbekDeveloper
