### ISSUE TITLE
DOCUMENTATION: Fix Completions Code Example

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Standard.AI.OpenAI#141]
![image](https://user-images.githubusercontent.com/1453985/226827339-e0eaf405-1645-4a60-be43-a9cfb4b96b3d.png)

We need an example that actually works.

**Comment by glhays** [comment]
I was thinking 
Array.ForEach(resultCompletion.Response.Prompts.Text, Console.WriteLine())
Console.Read()

**Comment by adavidoaiei** [comment]
I created too a Pull Request @hassanhabib https://github.com/hassanhabib/Standard.AI.OpenAI/pull/148

**Comment by tekprofessional** [comment]
@hassanhabib is this item done?  The readme will need to change again when the merge is done, to change Prompt to Prompts in the CompletionRequest

**Comment by glhays** [comment]
@tekprofessional Ricky merged this PR, look at the current Readme that the last line in the sample is the same as above.

**Comment by tekprofessional** [comment]
> @tekprofessional Ricky merged this PR, look at the current Readme that the last line in the sample is the same as above.

Got that. Maybe I should have asked if this item could be closed, since it looks like it's done.  Still getting used to participating in this community, thanks for the feedback

**Comment by Catalin-Andronie** [comment]
@hassanhabib We can close this issue since the README file contains a correct example. The issue was been closed via #148.
