### ISSUE TITLE
CONFIGURATIONS: Add support for different language models

### ISSUE THREAD

**Issue by TehWardy** [hassanhabib/Standard.AI.OpenAI#147]
OpenAI supports multiple LLM's for the same API.
We probably want to add an enum or something to the ApiConfigurations class that allows the consumer to pick a model to use.

I would do what the GPT site does itself and "default" to the current best choice that's not a beta so that this value is not required but having the choice would open up more options for consumers.

I've noticed this is in the request model, but my thinking is that this should be part of the client config so that a full conversation is given to a single LLM for conversational consistency.

**Comment by BrianLParker** [comment]
https://platform.openai.com/docs/api-reference/models/list

**Comment by TehWardy** [comment]
I think this was covered pretty well over recent live stream videos.
I'm gonna close this ticket unless @hassanhabib wishes to keep it open for some reason.
