### ISSUE TITLE
CODE RUB: Replace `application/json` and `Bearer` with Strongly Typed Values

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Standard.AI.OpenAI#186]
Assigning this to @tekprofessional

**Comment by tekprofessional** [comment]
@hassanhabib Can you provide some clarification? I see these values consumed by the wiremock in the CompletionClientTests.Prompts.

**Comment by hassanhabib** [comment]
@tekprofessional there are some native libraries in the .NET eco system that can help us find these values without having to hardcode them.

Find these libs and replace the hard-coded values mentioned in the title with strongly types models

**Comment by tekprofessional** [comment]
> @tekprofessional there are some native libraries in the .NET eco system that can help us find these values without having to hardcode them.
> 
> 
> 
> Find these libs and replace the hard-coded values mentioned in the title with strongly types models 

Thanks for the clarification
