### ISSUE TITLE
BROKERS: POST Audio File

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Standard.AI.OpenAI#210]
# The Ask
We need to develop an OpenAI Broker Method that POST Audio files and gets back transcriptions of these files

# How to Complete this Task
Here's some steps to complete this deliverable.

- Ensure that you understand how to natively talk to OpenAI API using Postman - (includes account & API key)
- Find the reference to integrating with OpenAI APIs [here](https://platform.openai.com/docs/api-reference/audio/create)
- Learn what Brokers are [here](https://github.com/hassanhabib/The-Standard/blob/master/1.%20Brokers/1.%20Brokers.md#1-brokers)
- Watch how The Standard Community developed a similar Broker for OpenAI [here](https://www.youtube.com/watch?v=YRLymNBSlqI&list=PLan3SCnsISTTl_MnGP6B78Nfu9Ix8G4mU&index=11)
- If you have any questions - ask The Standard Community [here](https://discord.com/invite/vdPZ7hS52X)

# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

**Comment by Catalin-Andronie** [comment]
I claim this issue

**Comment by YusC3** [comment]
If this Issue is not claimed, can I claim it? I see it was reopened.

**Comment by Catalin-Andronie** [comment]
> If this Issue is not claimed, can I claim it? I see it was reopened.
> 
> EDIT: I read up on the scenario, this makes sense.

@YusC3 I have pushed the code for it in #226 and was reverted in #242 since atm RESTFulSense does not have support to allow us to send a multipart/form-data request. Check the PR in [RESTFulSense #72](https://github.com/hassanhabib/RESTFulSense/pull/72).
