### ISSUE TITLE
CODE RUB: Update Exceptions List To Include Exceptions From ChatCompletion Client

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#220]
![image](https://user-images.githubusercontent.com/52498074/228206344-3396f63a-632f-4bb6-ad45-5d685d1da02d.png)
Example that shows completion client exceptions
Extend this to include chat completion client exceptions

**Comment by MirzayevDeveloper** [comment]
@MirzayevDeveloper It's on me

**Comment by ElbekDeveloper** [comment]
Duplicate #225
