### ISSUE TITLE
CODE RUB: Rename Unauthorized Exception Variable Names

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#249]
Look at the test that was written around 45:00 of the following stream 
https://www.youtube.com/watch?v=TL3fIV9F_ZA
and fix all method and exception varialble names to be not `unAuthorizationException` to be `authorizationException`

**Comment by AbbosHaydarov** [comment]
I took it @ElbekDeveloper
