### ISSUE TITLE
DATA: External Edit Model

### ISSUE THREAD

**Issue by rcruzfreelance** [hassanhabib/Standard.AI.OpenAI#253]

**Comment by rcruzfreelance** [comment]
Heres an example from api docs https://platform.openai.com/docs/api-reference/edits/create

**Comment by BrianLParker** [comment]
Hey Richardo. Make this a full Broker PR and Issue. Please copy the last Issue with all the Instructions provided.

**Comment by rcruzfreelance** [comment]
Sure thing
