### ISSUE TITLE
CODE RUB: Extract Mapping Logic From Method

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#259]
![image](https://user-images.githubusercontent.com/52498074/229269076-86f4741f-b8db-4759-ae3f-e4d17cd75e01.png)

**Comment by ElbekDeveloper** [comment]
The discussion starts after 1:00:00 of the following video:
https://www.youtube.com/watch?v=EzbYFCsFg5w

**Comment by diogod3** [comment]
I claim this
