### ISSUE TITLE
CODE RUB: Add `UsingPost()` in Acceptance Tests

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#260]
![image](https://user-images.githubusercontent.com/52498074/229269375-2613a51a-67f0-4623-a482-2d96f5c6d5c1.png)
This is the way we are initializing wiremock server in all tests except ai models 

The following is acceptance tests for retrieve all ai models: 
![image](https://user-images.githubusercontent.com/52498074/229269396-4a77d7ca-11ee-440b-b6a8-9055510fae6d.png)

if you are looking it says `.UsingGet()`, we should add such statement to post tests too. So you should say: `.UsingPost()`

**Comment by ElbekDeveloper** [comment]
The discussion starts after 1:05:00 of the following video: 
https://www.youtube.com/watch?v=EzbYFCsFg5w

**Comment by diogod3** [comment]
I claim this
