### ISSUE TITLE
MEDIUM FIX: Change `CompletionResponse` `Created` from `int` to `DateTimeOffset`

### ISSUE THREAD

**Issue by Gummimundur** [hassanhabib/Standard.AI.OpenAI#280]

**Comment by Gummimundur** [comment]
I claim this issue

**Comment by ElbekDeveloper** [comment]
@Gummimundur what is the reasoning behind this issue? 

I looked at the docs and the this is the response:
![image](https://user-images.githubusercontent.com/52498074/229355200-9e406378-1fae-4267-bd7a-16f5fd97725e.png)

Why do we need to change it to something that is not returned from API? Don't we lose this property if we change the name?

**Comment by Gummimundur** [comment]
@ElbekDeveloper `AIModel` uses `CreatedDate` and the service converts the returned `Created` to `CreatedDate`.
This issue was created to align the other services with this approach
