### ISSUE TITLE
MEDIUM FIX: Change `ChatCompletionResponse` `Created` from `int` to `DateTimeOffset`

### ISSUE THREAD

**Issue by Gummimundur** [hassanhabib/Standard.AI.OpenAI#282]

**Comment by Gummimundur** [comment]
I claim this issue

**Comment by hassanhabib** [comment]
@Gummimundur put some more documentation and add a tag here on this .

**Comment by Gummimundur** [comment]
# The Ask
We need our `ChatCompletion` service to return a `ChatCompletion` where `ChatCompletion.Response.Created` is replaced with `ChatCompletion.Response.CreatedDate` which is of type `DateTimeOffset`.

# How to Complete this Task
Here's some steps to complete this deliverable.
- Add a `CreatedDate` property to of type `DateTimeOffset` to `ChatCompletionResponse`
-  Modify the test `ShouldSendChatCompletionAsync` in `ChatCompletionServiceTests.Logics.Send` such that it maps the returned `ExternalChatCompletionResponse.Created` to `ChatCompletion.ChatCompletionResponse.CreatedDate` resulting in a failing test.
- Modify the service so the unit test `ShouldSendChatCompletionAsync` passes
- Modify the acceptance test `ShouldSendChatCompletionAsync` so it passes
- Remove the `Created` property from ChatCompletionResponse
- PR must be developed in a purist approach. One commit for a failing test then another for a passing test as shown in the videos from The Standard Community - PRs that have not met that criteria will be shutdown immediately
- See how a similar fix was done to the `ComplationService` here: #280 
- If you have any questions - ask The Standard Community [here](https://discord.com/invite/vdPZ7hS52X)
# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR
