### ISSUE TITLE
DOCUMENTATIONS: Add Rest of YouTube Links to Readme

### ISSUE THREAD

**Issue by hassanhabib** [hassanhabib/Standard.AI.OpenAI#300]
# The Ask
We need to update  the readme.md file in the project to have the rest of the sessions that we have recorded so far for this project.

## Links
Here's a link to our YouTube list [here](https://www.youtube.com/watch?v=JQnTpGV-7YA&list=PLan3SCnsISTTl_MnGP6B78Nfu9Ix8G4mU)

**Comment by ElbekDeveloper** [comment]
It would be great if we could provide the link to the playlist. What do you think Ustadh @hassanhabib?

**Comment by hassanhabib** [comment]
> It would be great if we could provide the link to the playlist. What do you think Ustadh @hassanhabib?

@ElbekDeveloper sounds good to me

**Comment by glhays** [comment]
I got this.
