### ISSUE TITLE
CODE RUB: Rename Property from `AllAIModels` to `AIModels`

### ISSUE THREAD

**Issue by Gummimundur** [hassanhabib/Standard.AI.OpenAI#301]
# The Ask
We need the naming of our `IAIModelsClient` to align with our other clients in the `OpenAIClient` exposure.

# How to Complete this Task
Here's some steps to complete this deliverable.
- Rename the `AllAIModels` property along with its references.

# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

**Comment by MirzayevDeveloper** [comment]
I claim this issue
