### ISSUE TITLE
DOCUMENTATIONS: Document `ALLAIModelsClient` Methods & Exceptions

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#306]
### The Ask

Write XML Documentation that pops up when using the method in Visual Studio through intellisense.  You should **only** document the exceptions that the method throws and explanation of exception in their corresponding files. For example:
NOTE: Example is for `CompletionsClient`, you should adjust this for `AllAIModelsClient`

``` csharp

        /// <exception cref="CompletionClientValidationException" />
        /// <exception cref="CompletionClientDependencyException" />
        /// <exception cref="CompletionClientServiceException" />
        ValueTask<Completion> PromptCompletionAsync(Completion completion);

```

``` csharp
    /// <summary>
    /// This exception is thrown when a validation error occurs while using the completion client.
    /// For example, if required data is missing or invalid.
    /// </summary>
    public class CompletionClientValidationException : Xeption
    {
       // code goes here...
    }

```

NOTE: Don't forget to take out the `Exceptions` sections of corresponding feature in the README.md (if exists). This is how it looks like for `Completions`: 
![image](https://user-images.githubusercontent.com/52498074/229711727-eb4df58e-f151-43a3-a132-b53ecf9d4d82.png)

### How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

### Measures of Success

Attach a screenshot of how it is showing the prompt in acceptance test and/or integration test projects where the method was used. Here is an example: 

![image](https://user-images.githubusercontent.com/52498074/229710006-5893cae1-9294-40d6-b77a-766580db480c.png)

**Comment by ElbekDeveloper** [comment]
Make sure https://github.com/hassanhabib/Standard.AI.OpenAI/pull/302 is closed and added to main branch.

**Comment by Catalin-Andronie** [comment]
I claim this issue
