### ISSUE TITLE
BROKERS: Create Fine-tune

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#308]
# The Ask
 The function fine-tunes the file and returns corresponding resopnse from OpenAI API

# How to Complete this Task
- Build the required request model
- Build the corresponding response model
- Implement `CreateFineTune();` method in brokers layer

# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

# Helpful Links
 - [Dedicated section in OpenAI API Reference](https://platform.openai.com/docs/api-reference/fine-tunes/create)
 - [How we have built other brokers](https://www.youtube.com/watch?v=YRLymNBSlqI)

**Comment by rcruzfreelance** [comment]
I claim this issue

**Comment by rcruzfreelance** [comment]
@hassanhabib @BrianLParker I'm trying to set up the response model for the fine tuning and this what I see from the docs:

![image](https://user-images.githubusercontent.com/53588704/230748203-471b97bf-9eab-4a63-b215-5a61ec77d326.png)

From what I'm having trouble is 3 properties:

- fine_tuned_model
- result_files
- validation_files

with the validation files I kind of figured that the result comes from this model

![image](https://user-images.githubusercontent.com/53588704/230748288-bde2baf8-a366-4b6c-a02f-31fbecdb6b8d.png)

But im not sure for the results_file or fine_tuned_model

**Comment by rcruzfreelance** [comment]
@hassanhabib  @BrianLParker  nvm I dont those are the proper models for validation files since this is more specific for the file and not the response. However I did find the result_files response looking into the finetune by id response example

**Comment by rcruzfreelance** [comment]
I think im going to use the same model of results for validation
