### ISSUE TITLE
CODE RUB: Add IDisposable to AIModelsClientTests

### ISSUE THREAD

**Issue by BrianLParker** [hassanhabib/Standard.AI.OpenAI#333]
# The Ask
`AIModelsClientTests` is creating warnings in the build pipeline.
![image](https://user-images.githubusercontent.com/8317299/230237210-f465ac44-c622-42d4-96fc-f6f1b842fb27.png)

# How to Complete this Task
Here's some steps to complete this deliverable.
- `AIModelsClientTests` needs to inherit `IDisposable`.

# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

**Comment by Javlonbek-dev** [comment]
I claim this issue
