### ISSUE TITLE
CODE RUB: Rename Variable in Test

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#335]
# The Ask
Look at the following screenshot, while initializing `NotFoundFileException` the name of the object is `invalidFileException`, it should have reflected the type itself
![image](https://user-images.githubusercontent.com/52498074/230287627-ae0080f5-97bd-41d4-86eb-b9bbc907738b.png)

# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

**Comment by khabibulladev** [comment]
I claim this issue
