### ISSUE TITLE
MINOR FIX: Fix `GetRandomBoolean` in `AIModelServiceTests`

### ISSUE THREAD

**Issue by Gummimundur** [hassanhabib/Standard.AI.OpenAI#347]
# The Ask
Our current implementation of `GetRandomBoolean` in `AIModelServiceTests` will always return `false` but we need it to return a random boolean.

# How to Complete this Task
- Fix `GetRandomBoolean` such that it returns a random boolean.
- You can see how a similar issue was fixed with #248.

# How to claim this issue?
- Post on this issue a comment that says: "I claim this issue"
- You will be given 24 hours to complete the issue - if no PR is opened within 24 hours someone else will claim it
- If you have an open PR but is inactive for more than 24 hours from the last review comment we will shutdown your PR

**Comment by Catalin-Andronie** [comment]
I claim this issue
