### ISSUE TITLE
RELEASES: Publis List All Files Package

### ISSUE THREAD

**Issue by ElbekDeveloper** [hassanhabib/Standard.AI.OpenAI#359]
# The Ask
Release the List All Files Feature

# How To Complete 
At this moment this task can only be performed by @hassanhabib
However, it's important that you learn how releasing is done - watch this session [here](https://www.youtube.com/watch?v=saU_5peAC-Y) to get this knowledge here

In the future releasing is going to be automated - there's an open issue for this here #195

**Comment by diogod3** [comment]
@hassanhabib You've already released, but I think you forgot to push the `csproj` with the updated version.

**Comment by hassanhabib** [comment]
@diogod3 done.
