### ISSUE TITLE
CODE RUB: LocalFiles Upgrade V2.10.0

### ISSUE THREAD

**Issue by glhays** [hassanhabib/Standard.AI.OpenAI#418]
Upgrade all LocalFiles Exceptions to v2.10.0 of The Standard
See the video explaining the process [here](https://youtu.be/oyJvszELGwE)

Whilst performing the upgrade please make all the tests private within the LocalFiles.
Currently the access modifiers are public on the method signatures.

Anyone wanting to take this, please leave a comment letting others know you are working on this.

**Comment by sammy-timalsina** [comment]
Hey @glhays , I am working on this code rub issue. Thanks.

**Comment by glhays** [comment]
@sammy-timalsina if you would please make all the access modifiers of the test methods in LocalFiles private. Thanks

**Comment by sammy-timalsina** [comment]
@glhays  Sure no problem, I made the changes, I will shortly commit it. Regards.
